coreWebApplications/coreMvcApp/Models/Employee.cs
namespace coreMvcApp.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public float Salary { get; set; }
    }
}

coreWebApplications/coreMvcApp/Models/ErrorViewModel.cs
namespace coreMvcApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

coreWebApplications/coreMvcApp/Models/Product.cs
namespace coreMvcApp.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public float Price { get; set; }
    }
}

coreWebApplications/coreMvcApp/Controllers/EmployeeController.cs
using coreMvcApp.Models;
using coreMvcApp.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace coreMvcApp.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            var employees = EmployeeRepository.GetAll();
            return View(employees);
        }
        public IActionResult Details(int id)
        {
            var employee = EmployeeRepository.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            EmployeeRepository.Add(employee);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var employee = EmployeeRepository.GetById(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        [HttpPost]
        public IActionResult Edit(Employee employee)
        {
            EmployeeRepository.Update(employee);
            return RedirectToAction("Index");
        }
    }
}

coreWebApplications/coreMvcApp/Controllers/HomeController.cs
using coreMvcApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace coreMvcApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

coreWebApplications/coreMvcApp/Controllers/ProductController.cs
using coreMvcApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace coreMvcApp.Controllers
{
    public class ProductController : Controller
    {
        static List<Product> products =
        [
            new Product { Id = 1, Name = "Wireless Mouse", Price = 200.50F },
            new Product { Id = 2, Name = "Wireless Keyboard", Price = 500.50F },
            new Product { Id = 3, Name = "Monitor Dell", Price = 1200.50F },
            new Product { Id = 4, Name = "Marshell Speaker", Price = 2000.50F },
        ];

        public IActionResult Index()
        {
            ViewBag.Message = "Product Management System";
            ViewBag.ProductCount = products.Count();
            ViewBag.Products = products;
            return View();
        }

        public IActionResult List()
        {
            ViewData["Message"] = "Product Management System";
            ViewData["ProductCount"] = products.Count();
            ViewData["Products"] = products;
            return View();
        }

        public IActionResult Method1()
        {
            TempData["Message"] = "Product Management System";
            TempData["ProductCount"] = products.Count();
            TempData["Products"] = products;
            return View();
        }
        public IActionResult Method2()
        {
            string? message = TempData["Message"] as string;
            if(!string.IsNullOrEmpty(message))
            {
                TempData["Message"] = message;
                return View();
            }
            return RedirectToAction("Index");
        }
    }
}

coreWebApplications/coreMvcApp/Views/Employee/Create.cshtml
@model coreMvcApp.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post" asp-action="Create">
    <div class="mb-3">
        <label for="Name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="mb-3">
        <label for="Salary" class="form-label">Salary</label>
        <input type="text" asp-for="Salary" class="form-control" />
    </div>

    <input type="submit" value="Create" class="btn btn-primary" />
</form>

coreWebApplications/coreMvcApp/Views/Employee/Details.cshtml
@model coreMvcApp.Models.Employee

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="card" style="width: 28rem;">
    <div class="card-header">
        Details of @Model.Name
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Id: @Model.Id</li>
        <li class="list-group-item">Name: @Model.Name</li>
        <li class="list-group-item">Salary: @Model.Salary</li>
    </ul>
    <div class="card-footer">
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

coreWebApplications/coreMvcApp/Views/Employee/Edit.cshtml
@model coreMvcApp.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post" asp-action="Edit">
    <div class="mb-3">
        <label for="Name" class="form-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="mb-3">
        <label for="Salary" class="form-label">Salary</label>
        <input type="text" asp-for="Salary" class="form-control" />
    </div>

    <input type="submit" value="Edit" class="btn btn-primary" />
</form>

coreWebApplications/coreMvcApp/Views/Employee/Index.cshtml
@model IList<coreMvcApp.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Salary</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Salary</td>
                <td>
                    <a asp-controller="Employee" asp-action="Details" asp-route-id="@item.Id">View Detail</a> |
                    <a asp-controller="Employee" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

coreWebApplications/coreMvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

coreWebApplications/coreMvcApp/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h3>@ViewBag.Message</h3>
<p>There are @ViewBag.ProductCount products in the list.</p>

<h5>Product List</h5>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in ViewBag.Products)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
            </tr>
        }
    </tbody>
</table>

coreWebApplications/coreMvcApp/Views/Product/List.cshtml
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<h3>@ViewData["Message"]</h3>
<p>There are @ViewData["ProductCount"] products in the list.</p>

<h5>Product List</h5>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewData["Products"] as List<Product>)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
            </tr>
        }
    </tbody>
</table>

coreWebApplications/coreMvcApp/Views/Product/Method1.cshtml
@{
    ViewData["Title"] = "Method1";
}

<h1>Method1</h1>

<h3>@TempData["Message"]</h3>
<p>There are @TempData["ProductCount"] products in the list.</p>

<h5>Product List</h5>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in TempData["Products"] as List<Product>)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Price</td>
            </tr>
        }
    </tbody>
</table>

@{
    TempData.Keep("Message");
}

<a asp-controller="Product" asp-action="Method2">Method 2</a>

coreWebApplications/coreMvcApp/Views/Product/Method2.cshtml
@{
    ViewData["Title"] = "Method2";
}

<h1>Method2</h1>

<h3>@TempData["Message"]</h3>

coreWebApplications/coreMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - coreMvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/coreMvcApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">coreMvcApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - coreMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>